src/Entity/Notation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotationRepository")
 */
class Notation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produits", inversedBy="notations")
     */
    private $Produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getProduit(): ?Produits
    {
        return $this->Produit;
    }

    public function setProduit(?Produits $Produit): self
    {
        $this->Produit = $Produit;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Repository\ClientRepository;
use App\Service\Cart\CartService;
use Stripe\Exception\ApiErrorException;
use Stripe\PaymentIntent;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    /**
     * @Route("/cart", name="cart")
     * @return Response
     */
    public function index(CartService $cartService)
    {
       $cartService->getFullCart();
       $cartService->getSousTotal();
       $cartService->getTva();
        $cartService->getTotal();

        return $this->render('cart/index.html.twig', [
            'controller_name' => 'CartController',
            'produits' => $cartService->getFullCart(),
            'sousTotal' => $cartService->getSousTotal(),
            'TVA' => $cartService->getTva(),
            'total' => $cartService->getTotal()
        ]);
    }

    /**
     *
     * @Route("/cart/edit{id}", name="cart_edit")
     * @param $id
     * @param CartService $cartService
     * @return RedirectResponse
     */

    public function edit($id, CartService $cartService)
    {
        $cartService->edit($id);

        return $this->redirectToRoute('cart');
    }


    /**
     * @Route("/cart/add{id}", name="cart_add")
     * @param $id
     * @param CartService $cartService
     * @return RedirectResponse
     */

    public function add($id, CartService $cartService)
    {
       $cartService->add($id);

        return $this->redirectToRoute('shop');
    }

    /**
     * @route("/cart/remove/{id}", name="cart_remove")
     * @param $id
     * @param CartService $cartService
     * @return RedirectResponse
     */
    public function remove($id, CartService $cartService)
    {

        $cartService->remove($id);
        return $this->redirectToRoute("cart");
    }

    /**
     * @param CartService $cartService
     * @return Response
     * @throws ApiErrorException
     * @Route("/cart/payment", name="cart_payment")
     */
    public function payment(CartService $cartService){

        $cartService->payment();

        return $this->render('cart/payment.html.twig',[
            'clientSecret'=>$cartService->payment()->client_secret
        ]);
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}{% endblock %}

{% block main %}
    <h1 class="text-center">Mon panier</h1>
    <section class="ftco-section ftco-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="cart-list">
                        {% for message in app.flashes('success') %}
                            <div class="d-flex justify-content-center" >
                                <div class="alert alert-success" style="max-width: 800px">
                                    {{ message }}
                                </div>
                            </div>
                        {% endfor %}
                        {% if produits | length > 0 %}
                        <table class="table">
                            <thead class="thead-primary">
                            <tr class="text-center">
                                <th>Supression</th>
                                <th class="d-none d-md-block">Image</th>
                                <th>Produit</th>
                                <th>Prix</th>
                                <th>Quantité</th>
                                <th>Unité</th>
                                <th>Actualiser</th>
                                <th>Total</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in produits %}
                            <form action="{{ path('cart_edit',{'id': item.produit.id}) }}" method="get">
                                <tr class="text-center">
                                    <td class="product-remove"><a href="{{path('cart_remove', {'id' : item.produit.id})}}"><span class="ion-ios-close"></span></a></td>

                                    <td class="image-prod  d-none d-sm-block">
                                        <a class="img" href="{{ path('shop_detail', {id: item.produit.id} ) }}"
                                           style="background-image:url({{ vich_uploader_asset(item.produit, 'imageFile') }});"></a>
                                    </td>

                                    <td class="product-name">
                                        <h3>{{item.produit.title}}</h3>

                                    </td>

                                    <td class="price">{{item.produit.price}}€</td>

                                    <td class="quantity">
                                        <div class="input-group justify-content-center" style="max-width: 200px">

                                            <div class="ml-2 ml-lg-4">
                                                <button class="btn btn-outline-primary js-btn-minus px-2" type="button">
                                                    &minus;
                                                </button>
                                            </div>
                                            <input type="text" id="qte" name="qte"  class="form-control text-center" value="{{ item.quantity }}" placeholder=""
                                                   aria-label="Example text with button addon"
                                                   aria-describedby="button-addon1">
                                            <div class="">
                                                <button class="btn btn-outline-primary js-btn-plus px-2" type="button">
                                                    &plus;
                                                </button>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="unity"> {{ item.produit.unite }}</td>
                                    <td class="bouton"  data-toggle="tooltip" title="Mettre à jour le prix">
                                        <button type="submit"><span class="ion-ios-refresh"></span></button>
                                    </td>
                                    <td class="total">{{(item.produit.price*item.quantity) | number_format(2, ',', '.')  }}€</td>
                                </tr><!-- END TR-->
                            </form>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                        <div class="text-center m-5">
                            <div class="text-center mb-5">
                                <h3 class="mb-3">Il n'y a pas de produit dans le panier</h3>
                                <a href="{{ path('shop') }}" class="btn btn-primary">
                                    Aller à la boutique
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row justify-content-end">
                    <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3>Code promo</h3>
                            <p>Entrez votre code promo si vous en avez un.</p>
                            <form action="#" class="info">
                                <div class="form-group">
                                    <label for="">Code promo</label>
                                    <input type="text" class="form-control text-left px-3" placeholder="">
                                </div>
                                <div class="d-flex justify-content-end">
                                    <a href="{{ path("checkout") }}" class="btn btn-primary py-3 px-4 m-3">Appliquer le
                                        code</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3>Estimation des frais de transports et de la TVA</h3>
                            <p>Entrez votre destination pour obtenir un devis d'expédition</p>
                            <form action="#" class="info">
                                <div class="form-group">
                                    <label for="">Pays</label>
                                    <input type="text" class="form-control text-left px-3" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="country">région</label>
                                    <input type="text" class="form-control text-left px-3" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="country">code postal</label>
                                    <input type="text" class="form-control text-left px-3" placeholder="">
                                </div>
                                <div class="d-flex justify-content-end">
                                    <a href="{{ path("checkout") }}" class="btn btn-primary py-3 px-4 m-3">Estimation</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4 mt-5 cart-wrap ftco-animate">
                        <div class="cart-total mb-3">
                            <h3>Montants du panier</h3>
                            <p class="d-flex">
                                <span>Sous-total</span>
                                <span>{{ sousTotal | number_format(2, ',', '.') }}€</span>
                            </p>
                            <p class="d-flex">
                                <span>TVA</span>
                                <span>{{TVA | number_format(2, ',', '.') }}€</span>
                            </p>
                            <p class="d-flex">
                                <span>Remise</span>
                                <span>0€</span>
                            </p>
                            <hr>
                            <p class="d-flex total-price">
                                <span>Total</span>
                                <span>{{total | number_format(2, ',', '.') }}€</span>
                            </p>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a href="{{ path("checkout") }}" class="btn btn-primary py-3 px-4">Passer commande</a>
                        </div>
                    </div>
                </div>
            </div>
    </section>
    {{ include("include/_newsletter.html.twig") }}
{% endblock %}

templates/cart/payment.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block main %}

    <form id="payment-form">
        <div id="card-element">
            <!-- Elements will create input elements here -->
        </div>

        <!-- We'll put the error messages in this element -->
        <div id="card-errors" role="alert"></div>

        <button id="submit" class="btn btn-primary">Payer</button>
    </form>

    <script> var clientSecret = "{{ clientSecret}}"</script>



    <script>

        var stripe = Stripe('pk_test_gaGdpBTousGEDE6F1rEQUxR300uoJgBrL1');

        var elements = stripe.elements();

        var form = document.getElementById('payment-form');



        form.addEventListener('submit', function(ev) {
            ev.preventDefault();
            stripe.confirmCardPayment(clientSecret, {
                payment_method: {
                    card: card,
                    billing_details: {
                        name: "{{app.user.username}}"
                    }
                }
            }).then(function(result) {
                if (result.error) {
                    // Show error to your customer (e.g., insufficient funds)
                    console.log(result.error.message);
                } else {
                    // The payment has been processed!
                    if (result.paymentIntent.status === 'succeeded') {

                        document.location.href="{{ path('commande_create') }}";

                        // Show a success message to your customer
                        // There's a risk of the customer closing the window before callback
                        // execution. Set up a webhook or plugin to listen for the
                        // payment_intent.succeeded event that handles any business critical
                        // post-payment actions.
                    }
                }
            });
        });

        /* stripe.confirmCardPayment may take several seconds to complet*/



        // Set up Stripe.js and Elements to use in checkout form
        var style = {
            base: {
                color: "#32325d",
            }
        };

        var card = elements.create("card", { style: style });
        card.mount("#card-element");

        cardElement.on('change', function(event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });
    </script>


{% endblock %}